name: Primeiro workflow

#aqui iremos incluir is eventos (gatilhos) para a execução da pipeline
on:
  push:
    branches:
      - main
      - master
      - develop

#um outro evento, será quando disparar um pull_request
  pull_request:
    branches:
      - main
      - master
      - develop


# agora iremos criar algumas tarefas,
# e uma lista de passos em cada um deles
jobs:
  job1:
    name: Primeira tarefa
    # executa essa tarefa primeiro antes do 2
    needs: job2
    runs-on: ubuntu-latest
    # Vamos incluir alguns passos para o primeiro job
    steps:
      - name: Passo 1
        run: echo "Executando o primeiro passo da pipeline"
      - name: Passo 2 
        run: echo "Executando o segundo passo"
      - name: Passo 3
        run: echo "Executando o terceiro passo"
        
  job2:
    name: Segunda tarefa
    runs-on: ubuntu-latest #outra maquina virtual
    steps:
    # vamos incluir mais alguns passos para o segundo job
      - name: Passo 4
        run: echo "Executando o quarto passo"
      - name: Passo 5
        run: echo "Executando o quinto passo"
      - name: Passo 6
        run: echo "Executando o sexto passo"
